WIP: input pipeline refactor
IndicoDataSolutions/finetune pull request #559
Opened 2020-04-06 13:22 UTC by benleetownsend

2020-04-06 13:27 UTC, madisonmay commented on finetune/base.py
> +                generator_fn, input_mode=InputMode.TRAIN, update_hook=update_hook
I think `generator_fn` needs to be `Xs` yeah?

2020-04-06 13:29 UTC, madisonmay commented on finetune/base.py
> +                generator_fn, input_mode=InputMode.TRAIN, update_hook=update_hook
If so -- can we add a test for the generator behavior?

2020-04-06 13:33 UTC, madisonmay commented on finetune/base_models/gpt2/featurizer.py
> +            tf.range(batch, dtype=tf.int32) * length + pool_idx,
Oh yikes -- was this straight up broken previously? Or were we updating config.max_length all the time or something.

2020-04-06 19:02 UTC, lhz1029 approved these changes
Thanks for doing this! Things look great!

2020-04-06 19:02 UTC, lhz1029 commented on finetune/base.py
> +            self.input_pipeline._text_to_ids(x) for x in X
Why is this change possible now?

2020-04-06 19:02 UTC, lhz1029 commented on finetune/encoding/target_encoders.py
> +        self.classes_ = list(set(lab_i["label"] for lab in labels for lab_i in lab) | {self.pad_token})
Why is this being flattened another layer?

2020-04-06 19:02 UTC, lhz1029 commented on finetune/input_pipeline.py
> +            LOGGER.warning("The dataset size is not adjusted for chunk long sequences when training from a generator")
It seems like _inference() always calls get_dataset_from_generator. Seems like we might have problems with chunk_long_sequences during prediction then?

2020-04-13 10:12 UTC, benleetownsend commented on finetune/encoding/target_encoders.py
> +        self.classes_ = list(set(lab_i["label"] for lab in labels for lab_i in lab) | {self.pad_token})
Previously the flattening was done by a sequence labellers post_data_initialisation method. this change gives all the label encoders the same interface.

2020-04-13 10:14 UTC, benleetownsend commented on finetune/input_pipeline.py
> +            LOGGER.warning("The dataset size is not adjusted for chunk long sequences when training from a generator")
I think the only problem might be the dataset length, but I think this is covered by ProgessBar's new chunked_length argument.

2020-04-13 10:16 UTC, benleetownsend commented on finetune/base.py
> +            self.input_pipeline._text_to_ids(x) for x in X
Format for inference was originally setup to cover the case where the inputs were different at this point for training and inference, which was the original sequence labeler before indico_to_finetune was removed. After this, format_for_inference was just a noop

2020-04-13 19:55 UTC, madisonmay commented on finetune/target_models/classifier.py
> +    def _predict_internal(self, zipped_data, probas=False, **kwargs):
I don't understand the distinction between `_predict` and `_predict_internal`.  From what I see so far `_predict` just calls `_predict_internal`?

2020-04-13 19:57 UTC, madisonmay commented on finetune/scheduler.py
> +        seq_features = model.featurize_sequence(x, *args, **kwargs)
Yup thank you.  Copy paste error on my part.

2020-04-13 20:01 UTC, madisonmay commented on finetune/target_models/comparison_regressor.py
> +        zipped_data = self.input_pipeline.zip_list_to_dict(X=pairs, context=context)
I believe this should be the same as normal predict() now?

2020-04-13 20:40 UTC, madisonmay commented on tests/test_sort_by_length.py
> +#        random.shuffle(fake_data)
Can just rm this line

2020-04-13 20:41 UTC, madisonmay requested changes
Looks good -- only question is around the _internal_predict fns

2020-04-15 18:10 UTC, madisonmay approved these changes

2020-04-16 01:56 UTC, lhz1029 approved these changes

2020-04-16 01:56 UTC, lhz1029 commented on finetune/base.py
> +
we probably want to get rid of all of this extra whitespace (other examples as well)

2020-04-16 01:56 UTC, lhz1029 commented on finetune/encoding/target_encoders.py
> +        self.classes_ = list(set(lab_i["label"] for lab in labels for lab_i in lab) | {self.pad_token})
:+1:

2020-04-16 01:56 UTC, lhz1029 commented on finetune/target_models/multiple_choice.py
> +        return super.featurize(self, zip(questions, answers), **kwargs)
Don't we want `super()`?

2020-04-16 11:42 UTC, merged